baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Presentazione Tesi'
theme = ["github.com/dzello/reveal-hugo"]
relativeURLs = true
uglyURLs = true

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
